// Generates THIRD_PARTY_LICENSES.md for everything SPECTER ships: runtime
// dependencies plus libraries bundled into the UI, and their transitive deps.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
const shipped = ['@mozilla/readability', 'react', 'react-dom', 'scheduler', 'zustand', 'lucide-react', 'marked', 'dompurify', 'lightweight-charts', 'fancy-canvas', 'use-sync-external-store']
const seen = new Map()
function visit(name) {
  if (seen.has(name)) return
  const dir = join('node_modules', name)
  const pj = join(dir, 'package.json')
  if (!existsSync(pj)) return
  const p = JSON.parse(readFileSync(pj, 'utf8'))
  const license = typeof p.license === 'string' ? p.license : p.license?.type ?? (p.licenses?.map((l) => l.type).join(' OR ') || 'UNKNOWN')
  seen.set(name, { version: p.version, license, homepage: p.homepage || (typeof p.repository === 'string' ? p.repository : p.repository?.url) || '' })
  for (const dep of Object.keys(p.dependencies ?? {})) visit(dep)
}
for (const n of [...Object.keys(pkg.dependencies ?? {}), ...shipped]) visit(n)
const rows = [...seen].sort(([a], [b]) => a.localeCompare(b))
let md = `# Third-party licenses\n\nSPECTER is MIT-licensed. It ships the following open-source components (generated by \`node scripts/licenses.mjs\`).\n\n`
md += `SPECTER also embeds **Electron** (MIT) and **Chromium** (BSD-3-Clause and others; see \`LICENSES.chromium.html\` in the installed application folder).\n\n`
md += `| Package | Version | License | Source |\n| --- | --- | --- | --- |\n`
for (const [name, r] of rows) md += `| ${name} | ${r.version} | ${r.license} | ${r.homepage.replace(/^git\+/, '').replace(/\.git$/, '')} |\n`
md += `\nCharts are rendered with TradingView **Lightweight Charts™** (Apache-2.0); attribution is shown in the chart UI as the license requires.\n`
writeFileSync('THIRD_PARTY_LICENSES.md', md)
console.log(`${rows.length} packages listed`)
